# Generated by Django 5.1.5 on 2025-04-20 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='is_premium_user',
        ),
        migrations.AddField(
            model_name='users',
            name='password',
            field=models.CharField(default=111, max_length=18),
            preserve_default=False,
        ),
    ]
